steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/\$PROJECT_ID/$GC_IMAGE_NAME:\$COMMIT_SHA', '.']
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/\$PROJECT_ID/cloud-run-demo-image:\$COMMIT_SHA']
  # Deploy image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '\$PROJECT_ID'
      - '--image'
      - 'gcr.io/\$PROJECT_ID/$GC_IMAGE_NAME:\$COMMIT_SHA'
      - '--region'
      - '$GC_REVISION'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/\$PROJECT_ID/$GC_IMAGE_NAME'
