#name: Deploy to Cloud Run
#
#options:
#  logging: CLOUD_LOGGING_ONLY
##  env: ["NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/", "NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6"]
#
#steps:
#  # Step 1: Build the container image using Google Cloud Buildpacks
#  # Step 1: Install dependencies
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['install']
#
#  # Step 2: Build the application
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['run', 'build']
#
#  # Step 3: Use Google Cloud Buildpacks to build and push the container image
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: [
#      'builds',
#      'submit',
#      '--pack',
#      '--tag',
#      'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website:latest'
#    ]
#  # Step 3: Deploy the container to Cloud Run
#  - name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: gcloud
#    args:
#      - 'run'
#      - 'deploy'
#      - 'dominos-website-next'
#      - '--image'
#      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
#      - '--platform'
#      - 'managed'
#      - '--region'
#      - 'me-west1' # Change to your preferred region me-west1
#      - '--ingress'
#      - 'internal-and-cloud-load-balancing'
#      - '--allow-unauthenticated'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ENV_TYPE=usa'
#images:
#  - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
#
#
##options:
##  logging: CLOUD_LOGGING_ONLY
##  env: ["NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/", "NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6"]
##steps:
##  - name: gcr.io/cloud-builders/docker
##    args:
##      - build
##      - '-t'
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##      - .
##  - name: gcr.io/cloud-builders/docker
##    args:
##      - push
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
##    args:
##      - 'run'
##      - 'deploy'
##      - 'dominos-website-next'
##      - '--image'
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##      - '--platform'
##      - 'managed'
##      - '--region'
##      - 'me-west1' # Change to your preferred region me-west1
##      - '--ingress'
##      - 'internal-and-cloud-load-balancing'
##      - '--allow-unauthenticated'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_ENV_TYPE=usa'
##    entrypoint: gcloud
##timeout: 1200s
##images:
##  - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##
#
##
##options:
##  logging: CLOUD_LOGGING_ONLY
##steps:
##  # Step 1: Install dependencies and build Next.js app
##  - name: 'node:16-slim'
##    id: 'Install dependencies and build app'
##    entrypoint: bash
##    args:
##      - '-c'
##      - |
##        npm install
##        npm run build
##
##  # Step 2: Copy pre-built files and build Docker image
##  - name: 'gcr.io/cloud-builders/docker'
##    id: 'Build Docker image'
##    args:
##      - build
##      - '-t'
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##      - .
##    # Pass pre-built files as artifacts
##    dir: .  # Ensure Docker build context includes .next and public directories
##
##  # Step 3: Push Docker image
##  - name: 'gcr.io/cloud-builders/docker'
##    id: 'Push Docker image'
##    args:
##      - push
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##
##  # Step 4: Deploy to Cloud Run
##  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
##    id: 'Deploy to Cloud Run'
##    args:
##      - 'run'
##      - 'deploy'
##      - 'dominos-website-next'
##      - '--image'
##      - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'
##      - '--platform'
##      - 'managed'
##      - '--region'
##      - 'me-west1'
##      - '--ingress'
##      - 'internal-and-cloud-load-balancing'
##      - '--allow-unauthenticated'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
##      - '--update-env-vars'
##      - 'NEXT_PUBLIC_ENV_TYPE=usa'
##    entrypoint: gcloud
##timeout: 1200s
##images:
##  - 'me-west1-docker.pkg.dev/cms-qa-9260/cloud-run-source-deploy/dominos_website_next/dominos-website'


options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Prepare the environment by setting permissions for directories and files
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - |
        chmod -R ugo+rw /output_bundle /workspace /env /yaml /config

  # Step 2: Run the preparer step to process apphosting.yaml and secrets
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - |
        /bin/preparer --apphostingyaml_filepath /workspace/apphosting.yaml \
        --project_id cms-qa-9260 \
        --apphostingyaml_output_filepath /yaml/apphostingyaml_processed \
        --dot_env_output_filepath /env/vars_with_secret_values \
        --backend_root_directory \
        --buildpack_config_output_filepath /config

  # Step 3: Build the container image using Firebase App Hosting Buildpacks
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - |
        /bin/sh -c /usr/local/bin/pack build me-west1-docker.pkg.dev/cms-qa-9260/firebaseapphosting-images/dominos-web-site-test:build-2024-11-26-001 \
        --network cloudbuild \
        --builder gcr.io/buildpacks/firebase-app-hosting-22/builder:a6002037d9ff7a22269e62f3e3438e516cb1ea4a \
        --path "$(cat /config/build-directory.txt)" \
        --volume output_bundle:/output_bundle:rw \
        --trust-builder \
        --env-file /env/vars_with_secret_values \
        --env X_GOOGLE_TARGET_PLATFORM=fah \
        --env FIREBASE_OUTPUT_BUNDLE_DIR=/output_bundle \
        --env FIREBASE_APP_HOSTING=1 \
        --env GOOGLE_BUILDABLE="$(cat /config/relative-project-directory.txt)" \
        --env FIREBASE_WEBAPP_CONFIG={"apiKey":"AIzaSyDWlzEVJu0xdylHOPMs7MrPumgtJZLSKqk","appId":"1:990840206620:web:c3167b6c8906f249aab6d9"}

  # Step 4: Publish the app to Cloud Run (using the processed apphosting.yaml)
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - |
        /bin/bash -c /bin/publisher \
        --apphostingyaml_filepath /yaml/apphostingyaml_processed \
        --output_bundle_dir /output_bundle \
        --output_filepath /output/output

# Optional: Add substitution for project and region
substitutions:
  _PROJECT_ID: cms-qa-9260
  _REGION: me-west1

timeout: '1200s'
