name: Deploy to Cloud Run

options:
  logging: CLOUD_LOGGING_ONLY
  env: ["NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/", "NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6"]

steps:
  #   Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dominos-website-next', '.']
  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dominos-website-next']

  # Step 3: Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dominos-website-next'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dominos-website-next'
      - '--platform'
      - 'managed'
      - '--region'
      - 'me-west1' # Change to your preferred region
      - '--ingress'
      - 'internal-and-cloud-load-balancing'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
      - '--update-env-vars'
      - 'NEXT_PUBLIC_ENV_TYPE=usa'
images:
  - 'gcr.io/$PROJECT_ID/dominos-website-next'

#options:
#  logging: CLOUD_LOGGING_ONLY


#steps:
#  - name: 'node'
#    entrypoint: 'npm'
#    args: ['install']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '--tag=gcr.io/$PROJECT_ID/dominos-website-next', '.']
#
#images: ['gcr.io/$PROJECT_ID/dominos-website-next']


#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dominos-website-next', '.']
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#      - 'run'
#      - 'deploy'
#      - 'dominos-website-next'
#      - '--image'
#      - 'gcr.io/$PROJECT_ID/dominos-website-next'
#      - '--platform'
#      - 'managed'
#      - '--region'
#      - 'me-west1' # Change to your preferred region
#      - '--ingress'
#      - 'internal-and-cloud-load-balancing'
#      - '--allow-unauthenticated'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ENV_TYPE=usa'
#images:
#  - 'gcr.io/$PROJECT_ID/dominos-website-next'

#name: Deploy to Cloud Run
#
#options:
#  logging: CLOUD_LOGGING_ONLY
#  env: ["NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/", "NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6"]
#
#steps:
#  - name: 'ubuntu'
#    args: ['echo', 'XXXXXX, after 600s']
##   Step 1: Build the Docker image
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dominos-website-next', '.']
#  # Step 2: Push the Docker image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/dominos-website-next']
#
#  # Step 3: Deploy the container to Cloud Run
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: gcloud
#    args:
#      - 'run'
#      - 'deploy'
#      - 'dominos-website-next'
#      - '--image'
#      - 'gcr.io/$PROJECT_ID/dominos-website-next'
#      - '--platform'
#      - 'managed'
#      - '--region'
#      - 'me-west1' # Change to your preferred region
#      - '--ingress'
#      - 'internal-and-cloud-load-balancing'
#      - '--allow-unauthenticated'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_HOST=https://ver-api.heilasystems.com/'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_MAP_API_KEY=AIzaSyCx6hd0AWOUm2c_PwcEYVxyPA-NEB4Ou04'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_CAPTCHA_KEY=6Le83UopAAAAABxxMZUciOsBoYXrsa3cods4b3I6'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ISR_REVALIDATE=900'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_APP_UUID=inmanage-employee'
#      - '--update-env-vars'
#      - 'NEXT_PUBLIC_ENV_TYPE=usa'
#images:
#  - 'gcr.io/$PROJECT_ID/dominos-website-next'

