options:
  logging: CLOUD_LOGGING_ONLY


steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/dominos-website-next', '.']
  - name: 'ubuntu'
    args: ['echo', 'Done']

images: ['gcr.io/$PROJECT_ID/dominos-website-next']
