steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-app']

  # Step 3: Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    env:
      - 'NEXT_PUBLIC_APP_HOST="https://ver-api.heilasystems.com/"x'
    args:
      - 'run'
      - 'deploy'
      - 'dominos-website-next'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dominos-website-next'
      - '--platform'
      - 'managed'
      - '--region'
      - 'me-west1' # Change to your preferred region
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/dominos-website-next'

