export const COUPON_SCREEN_TYPES = {
  ENTER_COUPON: 'ENTER_COUPON',
  LOADER: 'LOADER',
  GOT_COUPON: 'GOT_COUPON',
  BRANCH_COUPON: 'BRANCH_COUPON',
  EXPIRED_COUPON: 'EXPIRED_COUPON',
  ALREADY_USED_COUPON: 'ALREADY_USED_COUPON',
  ERROR_COUPON: 'ERROR_COUPON',
};
