export const MEDIA_ENUM = {
	IN_MENU: "inMenu",
	IN_MENU_MOBILE: "inMenuMobile",
	TOPPINGS_ROUND: "toppingsForRoundPizza",
	TOPPINGS_RECTANGLE: "toppingsForRectanglePizza",
	TOPPINGS_SQUARE: "toppingsForSquarePizza",
	TOPPINGS_VOLCANO: "toppingsForVolcanoPizza",
	SELECTED_MOBILE: "selectedMobile",
	UNSELECTED_MOBILE: "notSelectedMobile",
	SELECTED_WEB: "selectedWeb",
	UNSELECTED_WEB: "notSelectedWeb",
	DOUGH: "dough",
	STORE_PAGE: "storePage",
	TAG: "tag",
	WEB: "web",
	MOBILE: "mobile",
	WEB_MOBILE: "web-responsive",
	IN_POPUP: "InPopUp",
	IN_TRACKER: "inTracker",
	BUY_ME: "buyme",
};
